### PR TITLE
Issue: Python 3.11 compatibility

### PR DESCRIPTION
**Pull request by TmLev**
Sorry for creating PR, this repository doesn't have Issues tab.

Seems like `zprofile` can't be installed for Python of version 3.11

```logs
# poetry add zprofile
Using version ^1.0.12 for zprofile

Updating dependencies
Resolving dependencies... (6.1s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing zprofile (1.0.12): Failed

  CalledProcessError

  Command '['/minimax/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/minimax/.venv', '--no-deps', '/root/.cache/pypoetry/artifacts/e6/0a/62/27ea17761b31b06ba74ef346379237d31fd06a6b7a35390f1a74284c5a/zprofile-1.0.12.tar.gz']' returned non-zero exit status 1.

  at /usr/local/lib/python3.11/subprocess.py:571 in run
       567│             # We don't call process.wait() as .__exit__ does that for us.
       568│             raise
       569│         retcode = process.poll()
       570│         if check and retcode:
    →  571│             raise CalledProcessError(retcode, process.args,
       572│                                      output=stdout, stderr=stderr)
       573│     return CompletedProcess(process.args, retcode, stdout, stderr)
       574│ 
       575│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/minimax/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/minimax/.venv', '--no-deps', '/root/.cache/pypoetry/artifacts/e6/0a/62/27ea17761b31b06ba74ef346379237d31fd06a6b7a35390f1a74284c5a/zprofile-1.0.12.tar.gz'] errored with the following return code 1, and output: 
  Processing /root/.cache/pypoetry/artifacts/e6/0a/62/27ea17761b31b06ba74ef346379237d31fd06a6b7a35390f1a74284c5a/zprofile-1.0.12.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: zprofile
    Building wheel for zprofile (pyproject.toml): started
    Building wheel for zprofile (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error
    
    × Building wheel for zprofile (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [66 lines of output]
        running bdist_wheel
        running build
        running build_py
        creating build
        creating build/lib.linux-x86_64-cpython-311
        creating build/lib.linux-x86_64-cpython-311/zprofile
        copying zprofile/__init__.py -> build/lib.linux-x86_64-cpython-311/zprofile
        copying zprofile/builder.py -> build/lib.linux-x86_64-cpython-311/zprofile
        copying zprofile/profile_pb2.py -> build/lib.linux-x86_64-cpython-311/zprofile
        copying zprofile/__version__.py -> build/lib.linux-x86_64-cpython-311/zprofile
        copying zprofile/cpu_profiler.py -> build/lib.linux-x86_64-cpython-311/zprofile
        copying zprofile/wall_profiler.py -> build/lib.linux-x86_64-cpython-311/zprofile
        warning: build_py: byte-compiling is disabled, skipping.
        
        running build_ext
        building 'zprofile._profiler' extension
        creating build/temp.linux-x86_64-cpython-311
        creating build/temp.linux-x86_64-cpython-311/zprofile
        creating build/temp.linux-x86_64-cpython-311/zprofile/src
        gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Izprofile/src -I/minimax/.venv/include -I/usr/local/include/python3.11 -c zprofile/src/_profiler.cc -o build/temp.linux-x86_64-cpython-311/zprofile/src/_profiler.o -std=c++11
        In file included from zprofile/src/profiler.h:26,
                         from zprofile/src/_profiler.cc:18:
        zprofile/src/stacktraces.h: In member function ‘void AsyncSafeTraceMultiset::Reset()’:
        zprofile/src/stacktraces.h:72:52: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct AsyncSafeTraceMultiset::TraceData’ with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
           72 |   void Reset() { memset(traces_, 0, sizeof(traces_)); }
              |                                                    ^
        zprofile/src/stacktraces.h:89:10: note: ‘struct AsyncSafeTraceMultiset::TraceData’ declared here
           89 |   struct TraceData {
              |          ^~~~~~~~~
        gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Izprofile/src -I/minimax/.venv/include -I/usr/local/include/python3.11 -c zprofile/src/clock.cc -o build/temp.linux-x86_64-cpython-311/zprofile/src/clock.o -std=c++11
        gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Izprofile/src -I/minimax/.venv/include -I/usr/local/include/python3.11 -c zprofile/src/compat27.cc -o build/temp.linux-x86_64-cpython-311/zprofile/src/compat27.o -std=c++11
        gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Izprofile/src -I/minimax/.venv/include -I/usr/local/include/python3.11 -c zprofile/src/log.cc -o build/temp.linux-x86_64-cpython-311/zprofile/src/log.o -std=c++11
        gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Izprofile/src -I/minimax/.venv/include -I/usr/local/include/python3.11 -c zprofile/src/profiler.cc -o build/temp.linux-x86_64-cpython-311/zprofile/src/profiler.o -std=c++11
        In file included from zprofile/src/profiler.h:26,
                         from zprofile/src/profiler.cc:15:
        zprofile/src/stacktraces.h: In member function ‘void AsyncSafeTraceMultiset::Reset()’:
        zprofile/src/stacktraces.h:72:52: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct AsyncSafeTraceMultiset::TraceData’ with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
           72 |   void Reset() { memset(traces_, 0, sizeof(traces_)); }
              |                                                    ^
        zprofile/src/stacktraces.h:89:10: note: ‘struct AsyncSafeTraceMultiset::TraceData’ declared here
           89 |   struct TraceData {
              |          ^~~~~~~~~
        zprofile/src/profiler.cc: In static member function ‘static void Profiler::Handle(int, siginfo_t*, void*)’:
        zprofile/src/profiler.cc:166:32: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘frame’; did you mean ‘cframe’?
          166 |     PyFrameObject *frame = ts->frame;
              |                                ^~~~~
              |                                cframe
        zprofile/src/profiler.cc:170:41: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
          170 |       frames[num_frames].py_code = frame->f_code;
              |                                         ^~
        In file included from /usr/local/include/python3.11/Python.h:42,
                         from zprofile/src/profiler.h:18,
                         from zprofile/src/profiler.cc:15:
        /usr/local/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
           22 | typedef struct _frame PyFrameObject;
              |                ^~~~~~
        zprofile/src/profiler.cc:172:20: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
          172 |       frame = frame->f_back;
              |                    ^~
        In file included from /usr/local/include/python3.11/Python.h:42,
                         from zprofile/src/profiler.h:18,
                         from zprofile/src/profiler.cc:15:
        /usr/local/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
           22 | typedef struct _frame PyFrameObject;
              |                ^~~~~~
        error: command '/usr/bin/gcc' failed with exit code 1
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for zprofile
  Failed to build zprofile
  ERROR: Could not build wheels for zprofile, which is required to install pyproject.toml-based projects
  

  at /opt/poetry/venv/lib/python3.11/site-packages/poetry/utils/env.py:1540 in _run
      1536│                 output = subprocess.check_output(
      1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538│                 )
      1539│         except CalledProcessError as e:
    → 1540│             raise EnvCommandError(e, input=input_)
      1541│ 
      1542│         return decode(output)
      1543│ 
      1544│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /root/.cache/pypoetry/artifacts/e6/0a/62/27ea17761b31b06ba74ef346379237d31fd06a6b7a35390f1a74284c5a/zprofile-1.0.12.tar.gz

  at /opt/poetry/venv/lib/python3.11/site-packages/poetry/utils/pip.py:58 in pip_install
       54│ 
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│ 


```

### CODE REVIEW

**Comment by ghost** [comment]
This would be a big help for me.

**Comment by naboyu** [comment]
I believe this issue can be resolved by incorporating the changes from [this commit](https://github.com/GoogleCloudPlatform/cloud-profiler-python/commit/244e7ca370fc2261980626394f2d2f91ab180fd2).  
I've created a pull request for this change: #3.

**Comment by timpalpant** [comment]
I've pushed [version 1.0.13](https://pypi.org/project/zprofile/1.0.13/) which includes Python 3.11 support. Thanks @naboyu for contributing this!

**Comment by TmLev** [comment]
@timpalpant thank you!

Maybe consider making this repo full-fledged (and not a fork), so that the community can use the Issues tab?

**Pull request closed without merging**
